// Creating a User with valid Username, email and password
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Veenc0",
    //"email": "contactveenco@gmail.com",
    "password": "12346767676"
}

// Creating a User with invalid characters in username
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "--ääs",
   // "email": "contactveenco@gmail.com",
    "password": "123456789"
}

// Creating a User with invalid character in the email after the @ symbol
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Bastiii",
    //"email": "contactveenco@#.com",
    "password": "123456789"
}

// Creating a User with invalid email with nothing after the "."
###
# POST http://127.0.0.1/api/users
# Content-Type: application/json

# {
#     "userID": "Bastiii",
#     "email": "contactveenco@gmail.",
#     "password": "123456789"
# }

// Creating a User with invalid email without "@"
 ###
# POST http://127.0.0.1/api/users
# Content-Type: application/json

# {
#     "userID": "Bastiii",
#     //"email": "contactveenco_gmail.com",
#     "password": "123456789"
# }

// Creating a User with an email that already exists
###
# POST http://127.0.0.1/api/users
# Content-Type: application/json

# {
#     "userID": "Vasia",
#     //"email": "contactveenco@gmail.com",
#     "password": "123456789"
# }

// Creating a User with a username with less than 4 characters
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Vas",
    //"email": "contactveenca@gmail.com",
    "password": "123456789"
}

// Creating a User with a password that contains less that 8 characters
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Vasi",
    //"email": "contactveenca@gmail.com",
    "password": "1239"
}

// Creating a User with a password that contains invalid characters
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Vasi",
    //"email": "contactveenca@gmail.com",
    "password": "äü$$%%äü9"
}

// Creating a User with a password that contains invalid characters
###
POST http://127.0.0.1/api/users
Content-Type: application/json

{
    "userID": "Vasi",
    //"email": "contactveenca@gmail.com",
    "password": "123456799777"
}

